on: [push]

jobs:
 hello_world_job:
  runs-on: ubuntu-latest
  name: A job to say hello
  steps:
   # To use this repository's private action,
   # you must check out the repository
   - name: Extract branch name
     shell: bash
     run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
     id: extract_branch
   - name: Checkout
     uses: actions/checkout@v2
   - name: Hello world action step
     uses: ./ # Uses an action in the root directory
     id: hello
     with:
      who-to-greet: ${{ steps.extract_branch.outputs.branch }}
     # Use the output from the `hello` step
   - name: Get the production branch
     run: echo "The production branch is ${{ steps.hello.outputs.productionBranch }}"
   - name: Get the staging branch
     run: echo "The staging branch is ${{ steps.hello.outputs.stagingBranch }}"
   - name: Confirm push was to staging
     run: echo "The merge was made to staging is ${{ steps.hello.outputs.isPushToStaging }}"
   - name: Confirm push was to prod
     run: echo "The merge was made to prod is ${{ steps.hello.outputs.isPushToProduction }}"
   - name: Open PR current branch is staging
     if: ${{ steps.hello.outputs.isPushToStaging == 'true' }}
     id: pullmaster
     uses: tretuna/sync-branches@1.4.0
     with:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      FROM_BRANCH: ${{ steps.hello.outputs.stagingBranch }}
      TO_BRANCH: "master"
   - name: Open PR current branch is prod
     if: ${{ steps.hello.outputs.isPushToProduction == 'true' }}
     id: pullstaging
     uses: tretuna/sync-branches@1.4.0
     with:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      FROM_BRANCH: ${{ steps.hello.outputs.productionBranch }}
      TO_BRANCH: ${{ steps.hello.outputs.stagingBranch }}
