on:
 push:
  branches:
   - "release/**"

jobs:
 hello_world_job:
  runs-on: ubuntu-latest
  name: Automate opening hotfix PRs upstream
  steps:
   - name: Set output
     id: extract_current_tag
     run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/*/})"
   - name: Check output
     env:
      RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
     run: |
      echo $RELEASE_VERSION
      echo ${{ steps.vars.outputs.tag }}

   - name: Extract branch name
     shell: bash
     run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
     id: extract_branch
   - name: Checkout
     uses: actions/checkout@v2
   - name: Hotfix action step
     uses: ./.github/actions/open-pr-from-hotfix # Where the script will live
     id: hotfix
     with:
      current-tag: ${{ steps.extract_current_tag.output.tag}}
      current-branch: ${{ steps.extract_branch.outputs.branch }}
   # Use the output from the `hotfix` step
   - name: Get the production branch
     run: echo "The production branch is ${{ steps.hotfix.outputs.productionBranch }}"
   - name: Get the staging branch
     run: echo "The staging branch is ${{ steps.hotfix.outputs.stagingBranch }}"

   # Check whether push was made to staging or prod
   - name: Confirm push was to staging
     run: echo "The merge was made to staging is ${{ steps.hotfix.outputs.isPushToStaging }}"
   - name: Confirm push was to prod
     run: echo "The merge was made to prod is ${{ steps.hotfix.outputs.isPushToProduction }}"

   # Open PR against next upstream branch
   - name: Open PR against master if current branch is staging
     if: ${{ steps.hotfix.outputs.isPushToStaging == 'true' }}
     id: pullmaster
     uses: tretuna/sync-branches@1.4.0
     with:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      FROM_BRANCH: ${{ steps.hotfix.outputs.stagingBranch }}
      TO_BRANCH: "master"
   - name: Open PR against staging if current branch is prod
     if: ${{ steps.hotfix.outputs.isPushToProduction == 'true' }}
     id: pullstaging
     uses: tretuna/sync-branches@1.4.0
     with:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      FROM_BRANCH: ${{ steps.hotfix.outputs.productionBranch }}
      TO_BRANCH: ${{ steps.hotfix.outputs.stagingBranch }}
