on:
 push:
  branches:
   - "release/**"

jobs:
 hello_world_job:
  runs-on: ubuntu-latest
  name: Automate opening hotfix PRs upstream
  steps:
   - name: Extract branch name
     shell: bash
     run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
     id: extract_branch
   - name: Checkout
     uses: actions/checkout@v2
   - name: Hello world action step
     uses: ./ # Where the script will live
     id: hotfix
     with:
      who-to-greet: ${{ steps.extract_branch.outputs.branch }}
     # Use the output from the `hello` step
   - name: Get the production branch
     run: echo "The production branch is ${{ steps.hotfix.outputs.productionBranch }}"
   - name: Get the staging branch
     run: echo "The staging branch is ${{ steps.hotfix.outputs.stagingBranch }}"

   - name: Confirm push was to staging
     run: echo "The merge was made to staging is ${{ steps.hotfix.outputs.isPushToStaging }}"
   - name: Confirm push was to prod
     run: echo "The merge was made to prod is ${{ steps.hotfix.outputs.isPushToProduction }}"

   - name: Open PR current branch is staging
     if: ${{ steps.hotfix.outputs.isPushToStaging == 'true' }}
     id: pullmaster
     uses: tretuna/sync-branches@1.4.0
     with:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      FROM_BRANCH: ${{ steps.hotfix.outputs.stagingBranch }}
      TO_BRANCH: "master"
   - name: Open PR current branch is prod
     if: ${{ steps.hotfix.outputs.isPushToProduction == 'true' }}
     id: pullstaging
     uses: tretuna/sync-branches@1.4.0
     with:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      FROM_BRANCH: ${{ steps.hotfix.outputs.productionBranch }}
      TO_BRANCH: ${{ steps.hotfix.outputs.stagingBranch }}
